[package]
name = "probe-derp"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
probe = { version = "0.5" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
